
     INSERT INTO `DNA_TABLE`(ID,COUNT_DNA_MUTANT,COUNT_DNA_HUMAN) VALUES (1,10,100);
     INSERT INTO `DNA_TABLE`(ID,COUNT_DNA_MUTANT,COUNT_DNA_HUMAN) VALUES (2,40,100);
     INSERT INTO `DNA_TABLE`(ID,COUNT_DNA_MUTANT,COUNT_DNA_HUMAN) VALUES (3,35,100);

